INTRODUCTION TO NUMPY

In [1]:
import numpy as np

In [3]:
#creating a 1 dimensional array
arr_1d=np.array([1,2,3,4,5])
print(f"1 D array: {arr_1d}")

1 D array: [1 2 3 4 5]


In [8]:
#creating a 2 dimensinal array

array_2d=np.array([
    [2,3,4],
    [5,6,7]
])
array_2d

array([[2, 3, 4],
       [5, 6, 7]])

In [13]:
#creating an array of zeroes
zeros=np.zeros((3, 3))
print(f"Array of zeroes: {zeros}")

Array of zeroes: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
